### ISSUE TITLE
Spot Termination events are logged dozens of times

### ISSUE THREAD

**Issue by kemra102** [aws/aws-node-termination-handler#250] opened 2020-09-01 11:48 UTC
In our environments we are seeing a single Spot Termination event being logged in the region of 3-5 dozen times for the same event. All the log entries are 100% identical. This gives a false impression in our logging dashboard (and in our Grafana dashboards where we intend to surface this info to developers) that there has been multiple termination events when in fact only 1 has occurred.

**Comment by haugenj** [comment] 2020-09-03 23:22
The Monitor function is working as intended by running continuously and finding the event, but we should be deduplicating these events when they have the same EventID hash to skip sending them to the channel [here](https://github.com/aws/aws-node-termination-handler/blob/master/pkg/monitor/spotitn/spot-itn-monitor.go#L56)

**Comment by bwagner5** [comment] 2020-10-16 15:26
this was released in v1.8.0 https://github.com/aws/aws-node-termination-handler/releases/tag/v1.8.0

**Closed by bwagner5** 2020-10-16 15:26 UTC
Labels: Pending-Release, bug
