### ISSUE TITLE
Register and Deregister node to ALB Target group, when create new node or delete node

### ISSUE THREAD

**Issue by qnapnickchang** [aws/aws-node-termination-handler#394] opened 2021-03-29 05:53 UTC
Hi,

How to Register and Deregister node, when create new node or delete node?
I tested IMDS Processor,  when scale out node, the new node can't added to ALB target group.

Thanks

**Comment by jillmon** [comment] 2021-04-02 19:43
This appears to be a duplicate of https://github.com/aws/aws-node-termination-handler/issues/316.

**Closed by jillmon** 2021-04-02 19:43 UTC
Labels: Type: Question
