### ISSUE TITLE
Bad images on Public ECR?

### ISSUE THREAD

**Issue by tyrken** [aws/aws-node-termination-handler#533] opened 2021-11-18 00:36 UTC
Just started getting `standard_init_linux.go:228: exec user process caused: exec format error` on the v1.13.3 image from the public ECR repo, which looks to have just been pushed an hour ago.  This is on a standard x86_64 host (Amazon Linux 2).

Bad image example:
public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.13.3
sha256:63faf9b7bd275d505d150a0510813a9cb0cab9ad599a2b29d7cd70bd97209007

From the ECR gallery page (https://gallery.ecr.aws/aws-ec2/aws-node-termination-handler), a load of images were just pushed but luckily NOT the v1.13.4 image (sha256:259100e8c555e97170f0cb83578f2e5302d062d29e58ea3976ce54efce62f35b) which looks OK so far, and hence I've switched to that as a workaround.

**Comment by ophelan** [comment] 2021-11-18 00:43
I'm seeing the same behavior.

**Comment by ToniRib** [comment] 2021-11-18 00:43
So are we.

**Comment by cw-sakamoto** [comment] 2021-11-18 00:52
I upgraded to 1.14.0 and that solved the problem.

**Comment by artificial-aidan** [comment] 2021-11-18 00:56
A whole slew of bad images got pushed up.

```
/ # file node-termination-handler-1.13.1 
node-termination-handler-1.13.1: Mach-O 64-bit x86_64 executable
/ # file node-termination-handler-1.13.0
node-termination-handler-1.13.0: Mach-O 64-bit x86_64 executable
/ # file node-termination-handler-1.12.2
node-termination-handler-1.12.2: Mach-O 64-bit x86_64 executable
/ # file node-termination-handler-1.12.1
node-termination-handler-1.12.1: Mach-O 64-bit x86_64 executable
/ # file node-termination-handler-1.12.0
node-termination-handler-1.12.0: Mach-O 64-bit x86_64 executable
/ # file node-termination-handler-1.11.1
node-termination-handler-1.11.1: Mach-O 64-bit x86_64 executable
```

**Comment by lobosg** [comment] 2021-11-18 01:08
Any news? we are receiving the same error with v1.13.0

**Comment by sabw8217** [comment] 2021-11-18 01:22
Also hitting this.

**Comment by AdrienKuhn** [comment] 2021-11-18 01:34
We are facing the same issue.

For now, we retrieved the image digest from a working node and we set it on the deployment directly (instead of using the image tag)

Example for the `v1.12.2` version:

```
public.ecr.aws/aws-ec2/aws-node-termination-handler@sha256:0a322003234bad0d0139646388f1f1f41802cf04259bc41f032c9e32579a2a67
```

For helm, we can trick the release by using 

```yaml
image:
  repository: public.ecr.aws/aws-ec2/aws-node-termination-handler@sha256
  tag: 0a322003234bad0d0139646388f1f1f41802cf04259bc41f032c9e32579a2a67
```

**Comment by misterek** [comment] 2021-11-18 01:55
Moving to 1.14.0 also resolved the issue here.  This isn't a super great experience though.

**Comment by bseenu** [comment] 2021-11-18 03:17
Even i am impacted with this, is 1.13.3 image would be fixed soon, or recommend updating to 1.14.0 ?

**Comment by mper0003** [comment] 2021-11-18 04:22
Also impacted with this issue. Upgrade to 1.14.0 resolved it for us.

**Comment by Jooyoung-dable** [comment] 2021-11-18 04:33
I also faced this issue. Upgraded to 1.14.0 and It is fine.

**Comment by bwagner5** [comment] 2021-11-18 07:17
We are working on fixing the incorrect manifests that were pushed to ECR public.

**Comment by bwagner5** [comment] 2021-11-18 09:06
The bad manifests in the ECR public repo have been patched. Apologies for the inconvenience this caused.  Let us know if anyone is still experiencing issues.

**Comment by kanor1306** [comment] 2021-11-18 12:31
The version 1.14.0 seems to be now missing from the [ECR public gallery](https://gallery.ecr.aws/aws-ec2/aws-node-termination-handler). Is this expected?

**Comment by dougbyrne** [comment] 2021-11-18 16:00
I see the WIP tag was added, but wanted to mention that we are seeing the issue has returned.

**Comment by snay2** [comment] 2021-11-18 16:01
@dougbyrne Which version(s) and architecture(s) are you trying to pull? We will try to prioritize those in our mitigation while we address the root cause.

**Comment by bwagner5** [comment] 2021-11-18 16:12
@kanor1306 v1.14.0 is available: public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.14.0

**Comment by artificial-aidan** [comment] 2021-11-18 16:30
1.13.3, amd64

**Comment by kanor1306** [comment] 2021-11-18 17:13
> @kanor1306 v1.14.0 is available: public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.14.0

Yeah, sorry @bwagner5 my issues was totally unrelated to this.

**Comment by dougbyrne** [comment] 2021-11-18 17:25
@snay2 Image ID is public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.12.2 on linux AMD64

**Comment by bwagner5** [comment] 2021-11-18 17:26
All manifests have been patched. Let us if you are still having problems. NOTE: you may need to change the image pull policy to `Always` since the default is `IfNotPresent` which would cache the bad image pulled. Or you can roll the node.

**Comment by dougbyrne** [comment] 2021-11-18 17:28
Thanks, I see new pods are starting ok now.

**Comment by snay2** [comment] 2021-12-01 22:40
The issue is resolved now. Opened an issue with ECR to provide better metrics so we can prevent this from happening again: https://github.com/aws/containers-roadmap/issues/1587

**Closed by snay2** 2021-12-01 22:40 UTC
Labels: Type: Bug, Priority: Critical, Status: Work in Progress
