### ISSUE TITLE
Queue Processor: should be multithreaded, cannot keep up

### ISSUE THREAD

**Issue by universam1** [aws/aws-node-termination-handler#310] opened 2020-12-08 13:53 UTC
It turns out that messages queue up if the NTH cannot continue! The more nodes are rotating the higher the chance that it will not catch up in time - we see this happening.
For instance NTH is busy retrying to evict an unevictable pod (because of PDB limits) it will not process other messages and eventually be too late.

Its a design dept from previous implementation that was always single processed on every node.

Reason: The NTH maybe in a retry loop to evict pods and does not continue to process other events.

Solution: Every event message should spin up a Go-routing that processes independently in order no to delay other messages

**Comment by haugenj** [comment] 2020-12-08 21:27
I'm not sure I agree with spinning up more threads to process these events, that seems like a symptomatic fix that wouldn't address the underlying root cause of why NTH is failing to process events. If we don't solve the hanging issue, I fear we could spin up many threads that all end up hanging, leading to a memory leak. Thoughts?

**Comment by universam1** [comment] 2020-12-09 08:20
I think these are two independent issues which might theoretically build up but I cannot believe that can become a memory leak that soon. Goroutines are so lightweight that they should always be used whereever applicable.

But I definitely see in our clusters when a couple of nodes roll at the same time, and NTH is busy retrying to evict an unevictable pod (because of PDB limits) it will not process other messages and this is terrible because it is a desaster later!

To me that problem questions the whole Queue implementation

**Comment by haugenj** [comment] 2020-12-09 17:10
I see, I'll mark this as an enhancement for now.

You _could_ run multiple replicas of NTH, but I think you'll still run into problems due to #307

**Comment by universam1** [comment] 2020-12-21 10:32
@haugenj @bwagner5 submitted a PR #307  contribution that addresses this issue, thank you for considering

**Comment by bwagner5** [comment] 2021-01-06 17:33
released in https://github.com/aws/aws-node-termination-handler/releases/tag/v1.12.0

**Closed by bwagner5** 2021-01-06 17:33 UTC
Labels: Pending-Release, enhancement
